[features]
seeds = false
skip-lint = false

[programs.localnet]
mention_market = "AJ4XSwJoh2C8vmd8U7xhpzMkzkZZPaBRpbfpkmm4DmeN"

[programs.devnet]
mention_market = "AJ4XSwJoh2C8vmd8U7xhpzMkzkZZPaBRpbfpkmm4DmeN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deployer-keypair.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
