[features]
seeds = false
skip-lint = false

[programs.localnet]
mention_market_usdc_amm = "9kSuebrHKKnFsgFcv5fc8S2gBazHA9Gki2NEWt2ft9tk"

[programs.devnet]
mention_market_usdc_amm = "9kSuebrHKKnFsgFcv5fc8S2gBazHA9Gki2NEWt2ft9tk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deployer-keypair.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
startup_wait = 30000
bind_address = "127.0.0.1"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mention-market-usdc-amm.ts"
