[features]
seeds = false
skip-lint = false

[programs.localnet]
mention_market = "AJ4XSwJoh2C8vmd8U7xhpzMkzkZZPaBRpbfpkmm4DmeN"
mention_market_amm = "2oKQaiKx3C2qpkqFYGDdvEGTyBDJP85iuQtJ5vaPdFrU"

[programs.devnet]
mention_market = "AJ4XSwJoh2C8vmd8U7xhpzMkzkZZPaBRpbfpkmm4DmeN"
mention_market_amm = "2oKQaiKx3C2qpkqFYGDdvEGTyBDJP85iuQtJ5vaPdFrU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deployer-keypair.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
startup_wait = 30000
bind_address = "127.0.0.1"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
