'use client'

import { useMemo } from 'react'
import Header from '@/components/Header'
import MarketCard from '@/components/MarketCard'
import Footer from '@/components/Footer'

export default function Home() {
  // Calculate event times
  const allMarkets = useMemo(() => {
    const now = new Date()
    
    return [
      {
        id: 'trump-speech',
        category: 'SPEECHES',
        title: "TRUMP IOWA RALLY",
        eventTime: new Date(now.getTime() + 2 * 60 * 60 * 1000),
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPwsL0smxRVROhCkwShqqarIa-4xnAdVdAomChQJ_T5mRI0s77w-xoaIXYP2m8tRl-uEGpY2db-WBf6yZIfORA6Azp8_G7mOSTRPFRKHgyuo-4Ltlj_aMHH0t0PkSvdDO95rJOZpBgoS7jAKqkQ_7C86iSDgLJC9vDfV4YSshAaEhuIv2qI0WDcGs0VSLKNYTrz72KduCuH-fH8XBkROiM1zDK2dJlV6R0sCiMjP_Y3Ml19Uglhnihkb8ZD1prCuWa0i_wip0TXSI',
        imageAlt: 'Donald Trump',
        imageFilter: 'grayscale(1) contrast(2) brightness(1.2)',
        featured: false,
        volume: 125000,
        words: [
          { word: 'IMMIGRATION', yesPrice: '0.72', noPrice: '0.28' },
          { word: 'ECONOMY', yesPrice: '0.65', noPrice: '0.35' },
          { word: 'CHINA', yesPrice: '0.58', noPrice: '0.42' },
          { word: 'BORDER', yesPrice: '0.81', noPrice: '0.19' },
          { word: 'TAXES', yesPrice: '0.45', noPrice: '0.55' },
          { word: 'JOBS', yesPrice: '0.67', noPrice: '0.33' },
        ],
      },
      {
        id: 'drake-album',
        category: 'MUSIC',
        title: 'DRAKE - FOR ALL THE DOGS',
        eventTime: new Date(now.getTime() + 4 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        imageAlt: 'Music recording',
        imageFilter: 'grayscale(1) contrast(1.8) brightness(0.9)',
        featured: false,
        volume: 89000,
        words: [
          { word: 'LOVE', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'MONEY', yesPrice: '0.76', noPrice: '0.24' },
          { word: 'GIRL', yesPrice: '0.82', noPrice: '0.18' },
          { word: 'PAIN', yesPrice: '0.54', noPrice: '0.46' },
          { word: 'TRUST', yesPrice: '0.61', noPrice: '0.39' },
          { word: 'FAME', yesPrice: '0.73', noPrice: '0.27' },
        ],
      },
      {
        id: 'rogan-musk',
        category: 'PODCASTS',
        title: 'JOE ROGAN EP #2054',
        eventTime: new Date(now.getTime() + 5 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80',
        imageAlt: 'Podcast microphone',
        imageFilter: 'grayscale(1) contrast(2) brightness(1.0)',
        featured: false,
        volume: 156000,
        words: [
          { word: 'TESLA', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'SPACEX', yesPrice: '0.87', noPrice: '0.13' },
          { word: 'AI', yesPrice: '0.94', noPrice: '0.06' },
          { word: 'MARS', yesPrice: '0.68', noPrice: '0.32' },
          { word: 'TWITTER', yesPrice: '0.79', noPrice: '0.21' },
          { word: 'FUTURE', yesPrice: '0.85', noPrice: '0.15' },
        ],
      },
      {
        id: 'colbert-show',
        category: 'TV SHOWS',
        title: 'THE LATE SHOW - DECEMBER 30',
        eventTime: new Date(now.getTime() + 6 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80',
        imageAlt: 'TV studio',
        imageFilter: 'grayscale(1) contrast(1.9) brightness(1.1)',
        featured: false,
        volume: 67000,
        words: [
          { word: 'TRUMP', yesPrice: '0.96', noPrice: '0.04' },
          { word: 'POLITICS', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'ELECTION', yesPrice: '0.71', noPrice: '0.29' },
          { word: 'CONGRESS', yesPrice: '0.59', noPrice: '0.41' },
          { word: 'JOKE', yesPrice: '0.93', noPrice: '0.07' },
          { word: 'AUDIENCE', yesPrice: '0.84', noPrice: '0.16' },
        ],
      },
      {
        id: 'dune-script',
        category: 'MOVIES',
        title: 'DUNE: PART THREE PREMIERE',
        eventTime: new Date(now.getTime() + 8 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80',
        imageAlt: 'Movie theater',
        imageFilter: 'grayscale(1) contrast(2) brightness(0.85)',
        featured: false,
        volume: 98000,
        words: [
          { word: 'SPICE', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'DESERT', yesPrice: '0.87', noPrice: '0.13' },
          { word: 'PROPHECY', yesPrice: '0.74', noPrice: '0.26' },
          { word: 'EMPEROR', yesPrice: '0.82', noPrice: '0.18' },
          { word: 'WORM', yesPrice: '0.69', noPrice: '0.31' },
          { word: 'POWER', yesPrice: '0.78', noPrice: '0.22' },
        ],
      },
      {
        id: 'mr-beast-video',
        category: 'YOUTUBE',
        title: 'MRBEAST $1M CHALLENGE',
        eventTime: new Date(now.getTime() + 9 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&q=80',
        imageAlt: 'YouTube content',
        imageFilter: 'grayscale(1) contrast(1.7) brightness(0.95)',
        featured: false,
        volume: 234000,
        words: [
          { word: 'INSANE', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'CRAZY', yesPrice: '0.92', noPrice: '0.08' },
          { word: 'DOLLAR', yesPrice: '0.94', noPrice: '0.06' },
          { word: 'WINNER', yesPrice: '0.86', noPrice: '0.14' },
          { word: 'SUBSCRIBE', yesPrice: '0.78', noPrice: '0.22' },
          { word: 'CHALLENGE', yesPrice: '0.91', noPrice: '0.09' },
        ],
      },
      {
        id: 'nba-finals-cast',
        category: 'SPORTS CAST',
        title: 'NBA FINALS GAME 7',
        eventTime: new Date(now.getTime() + 10 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800&q=80',
        imageAlt: 'NBA game',
        imageFilter: 'grayscale(1) contrast(2.1) brightness(1.0)',
        featured: false,
        volume: 178000,
        words: [
          { word: 'THREE', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'TIMEOUT', yesPrice: '0.76', noPrice: '0.24' },
          { word: 'FOUL', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'CHAMPIONSHIP', yesPrice: '0.84', noPrice: '0.16' },
          { word: 'DEFENSE', yesPrice: '0.79', noPrice: '0.21' },
          { word: 'CLUTCH', yesPrice: '0.67', noPrice: '0.33' },
        ],
      },
      {
        id: 'world-cup-cast',
        category: 'SPORTS CAST',
        title: 'WORLD CUP FINAL 2026',
        eventTime: new Date(now.getTime() + 11 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80',
        imageAlt: 'World Cup',
        imageFilter: 'grayscale(1) contrast(2) brightness(0.9)',
        featured: false,
        volume: 145000,
        words: [
          { word: 'GOAL', yesPrice: '0.93', noPrice: '0.07' },
          { word: 'PENALTY', yesPrice: '0.71', noPrice: '0.29' },
          { word: 'OFFSIDE', yesPrice: '0.64', noPrice: '0.36' },
          { word: 'CORNER', yesPrice: '0.82', noPrice: '0.18' },
          { word: 'YELLOW', yesPrice: '0.77', noPrice: '0.23' },
          { word: 'CHAMPION', yesPrice: '0.86', noPrice: '0.14' },
        ],
      },
      {
        id: 'league-patch',
        category: 'PATCH NOTES',
        title: 'LEAGUE OF LEGENDS 14.5 NOTES',
        eventTime: new Date(now.getTime() + 12 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
        imageAlt: 'Gaming',
        imageFilter: 'grayscale(1) contrast(1.5) brightness(0.8)',
        featured: false,
        volume: 72000,
        words: [
          { word: 'NERF', yesPrice: '0.84', noPrice: '0.16' },
          { word: 'BUFF', yesPrice: '0.79', noPrice: '0.21' },
          { word: 'BALANCE', yesPrice: '0.72', noPrice: '0.28' },
          { word: 'DAMAGE', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'ADJUSTED', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'REWORK', yesPrice: '0.56', noPrice: '0.44' },
        ],
      },
      {
        id: 'valorant-patch',
        category: 'PATCH NOTES',
        title: 'VALORANT EPISODE 8 ACT 1',
        eventTime: new Date(now.getTime() + 13 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
        imageAlt: 'Valorant',
        imageFilter: 'grayscale(1) contrast(1.7) brightness(0.85)',
        featured: false,
        volume: 87000,
        words: [
          { word: 'AGENT', yesPrice: '0.87', noPrice: '0.13' },
          { word: 'WEAPON', yesPrice: '0.76', noPrice: '0.24' },
          { word: 'MAP', yesPrice: '0.68', noPrice: '0.32' },
          { word: 'ABILITY', yesPrice: '0.92', noPrice: '0.08' },
          { word: 'FIXED', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'UPDATE', yesPrice: '0.94', noPrice: '0.06' },
        ],
      },
      {
        id: 'apple-keynote',
        category: 'TECH EVENTS',
        title: 'APPLE WWDC 2025 KEYNOTE',
        eventTime: new Date(now.getTime() + 14 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80',
        imageAlt: 'Apple',
        imageFilter: 'grayscale(1) contrast(2) brightness(1.0)',
        featured: false,
        volume: 201000,
        words: [
          { word: 'IPHONE', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'INNOVATION', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'AMAZING', yesPrice: '0.94', noPrice: '0.06' },
          { word: 'REVOLUTIONARY', yesPrice: '0.73', noPrice: '0.27' },
          { word: 'PRIVACY', yesPrice: '0.81', noPrice: '0.19' },
          { word: 'ECOSYSTEM', yesPrice: '0.76', noPrice: '0.24' },
        ],
      },
      {
        id: 'google-io',
        category: 'TECH EVENTS',
        title: 'GOOGLE I/O 2025 DAY 1',
        eventTime: new Date(now.getTime() + 15 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&q=80',
        imageAlt: 'Google',
        imageFilter: 'grayscale(1) contrast(1.7) brightness(1.0)',
        featured: false,
        volume: 189000,
        words: [
          { word: 'AI', yesPrice: '0.96', noPrice: '0.04' },
          { word: 'ANDROID', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'CLOUD', yesPrice: '0.74', noPrice: '0.26' },
          { word: 'SEARCH', yesPrice: '0.81', noPrice: '0.19' },
          { word: 'DEVELOPER', yesPrice: '0.86', noPrice: '0.14' },
          { word: 'GEMINI', yesPrice: '0.92', noPrice: '0.08' },
        ],
      },
      {
        id: 'tesla-earnings',
        category: 'EARNINGS',
        title: 'TESLA Q4 2024 EARNINGS CALL',
        eventTime: new Date(now.getTime() + 16 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
        imageAlt: 'Tesla',
        imageFilter: 'grayscale(1) contrast(1.9) brightness(0.95)',
        featured: false,
        volume: 134000,
        words: [
          { word: 'PROFIT', yesPrice: '0.78', noPrice: '0.22' },
          { word: 'GROWTH', yesPrice: '0.84', noPrice: '0.16' },
          { word: 'DELIVERY', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'MARGIN', yesPrice: '0.72', noPrice: '0.28' },
          { word: 'GUIDANCE', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'PRODUCTION', yesPrice: '0.86', noPrice: '0.14' },
        ],
      },
      {
        id: 'nvidia-earnings',
        category: 'EARNINGS',
        title: 'NVIDIA Q1 2025 EARNINGS',
        eventTime: new Date(now.getTime() + 17 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&q=80',
        imageAlt: 'Technology',
        imageFilter: 'grayscale(1) contrast(1.8) brightness(0.9)',
        featured: false,
        volume: 167000,
        words: [
          { word: 'REVENUE', yesPrice: '0.93', noPrice: '0.07' },
          { word: 'DATACENTER', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'GAMING', yesPrice: '0.76', noPrice: '0.24' },
          { word: 'AI', yesPrice: '0.96', noPrice: '0.04' },
          { word: 'DEMAND', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'CHIP', yesPrice: '0.88', noPrice: '0.12' },
        ],
      },
      {
        id: 'musk-reddit-ama',
        category: 'REDDIT AMA',
        title: 'ELON MUSK AMA - DEC 2024',
        eventTime: new Date(now.getTime() + 18 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1616509091215-57bbece93654?w=800&q=80',
        imageAlt: 'Reddit',
        imageFilter: 'grayscale(1) contrast(1.6) brightness(0.95)',
        featured: false,
        volume: 143000,
        words: [
          { word: 'TESLA', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'SPACEX', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'MARS', yesPrice: '0.74', noPrice: '0.26' },
          { word: 'TWITTER', yesPrice: '0.82', noPrice: '0.18' },
          { word: 'CRYPTO', yesPrice: '0.67', noPrice: '0.33' },
          { word: 'MEME', yesPrice: '0.79', noPrice: '0.21' },
        ],
      },
      {
        id: 'obama-ama',
        category: 'REDDIT AMA',
        title: 'PRESIDENT OBAMA AMA 2025',
        eventTime: new Date(now.getTime() + 19 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800&q=80',
        imageAlt: 'Obama',
        imageFilter: 'grayscale(1) contrast(2) brightness(1.0)',
        featured: false,
        volume: 198000,
        words: [
          { word: 'HEALTHCARE', yesPrice: '0.87', noPrice: '0.13' },
          { word: 'DEMOCRACY', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'CLIMATE', yesPrice: '0.84', noPrice: '0.16' },
          { word: 'HOPE', yesPrice: '0.78', noPrice: '0.22' },
          { word: 'CHANGE', yesPrice: '0.82', noPrice: '0.18' },
          { word: 'AMERICA', yesPrice: '0.93', noPrice: '0.07' },
        ],
      },
      {
        id: 'nyt-article',
        category: 'ARTICLES',
        title: 'NY TIMES FRONT PAGE JAN 1',
        eventTime: new Date(now.getTime() + 20 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
        imageAlt: 'Newspaper',
        imageFilter: 'grayscale(1) contrast(2.2) brightness(0.9)',
        featured: false,
        volume: 54000,
        words: [
          { word: 'CRISIS', yesPrice: '0.76', noPrice: '0.24' },
          { word: 'ELECTION', yesPrice: '0.83', noPrice: '0.17' },
          { word: 'PRESIDENT', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'BREAKING', yesPrice: '0.68', noPrice: '0.32' },
          { word: 'CONFLICT', yesPrice: '0.72', noPrice: '0.28' },
          { word: 'ECONOMY', yesPrice: '0.88', noPrice: '0.12' },
        ],
      },
      {
        id: 'biden-speech-timing',
        category: 'TIMINGS',
        title: 'BIDEN STATE OF UNION LENGTH',
        eventTime: new Date(now.getTime() + 21 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
        imageAlt: 'Biden speech',
        imageFilter: 'grayscale(1) contrast(1.9) brightness(1.0)',
        featured: false,
        volume: 78000,
        words: [
          { word: '60MIN', yesPrice: '0.45', noPrice: '0.55' },
          { word: '70MIN', yesPrice: '0.68', noPrice: '0.32' },
          { word: '80MIN', yesPrice: '0.72', noPrice: '0.28' },
          { word: '90MIN', yesPrice: '0.54', noPrice: '0.46' },
          { word: 'APPLAUSE', yesPrice: '0.94', noPrice: '0.06' },
          { word: 'STANDING', yesPrice: '0.87', noPrice: '0.13' },
        ],
      },
      {
        id: 'got-finale',
        category: 'TV SHOWS',
        title: 'HOUSE OF DRAGON S3 FINALE',
        eventTime: new Date(now.getTime() + 22 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80',
        imageAlt: 'TV show',
        imageFilter: 'grayscale(1) contrast(1.8) brightness(0.85)',
        featured: false,
        volume: 112000,
        words: [
          { word: 'DRAGON', yesPrice: '0.96', noPrice: '0.04' },
          { word: 'DEATH', yesPrice: '0.88', noPrice: '0.12' },
          { word: 'BATTLE', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'KING', yesPrice: '0.84', noPrice: '0.16' },
          { word: 'THRONE', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'BETRAYAL', yesPrice: '0.76', noPrice: '0.24' },
        ],
      },
      {
        id: 'minecraft-video',
        category: 'YOUTUBE',
        title: 'DREAM MINECRAFT MANHUNT #50',
        eventTime: new Date(now.getTime() + 23 * 60 * 60 * 1000),
        imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&q=80',
        imageAlt: 'Minecraft',
        imageFilter: 'grayscale(1) contrast(1.7) brightness(0.9)',
        featured: false,
        volume: 187000,
        words: [
          { word: 'SPEEDRUN', yesPrice: '0.89', noPrice: '0.11' },
          { word: 'CLUTCH', yesPrice: '0.82', noPrice: '0.18' },
          { word: 'DIAMOND', yesPrice: '0.91', noPrice: '0.09' },
          { word: 'NETHER', yesPrice: '0.87', noPrice: '0.13' },
          { word: 'ENDER', yesPrice: '0.94', noPrice: '0.06' },
          { word: 'PEARL', yesPrice: '0.78', noPrice: '0.22' },
        ],
      },
    ]
  }, [])

  // Filter markets based on selected category
  const markets = useMemo(() => {
    return allMarkets
  }, [allMarkets])

  return (
    <div className="relative flex h-auto min-h-screen w-full flex-col overflow-x-hidden">
      <div className="layout-container flex h-full grow flex-col">
        <div className="px-4 md:px-10 lg:px-20 flex flex-1 justify-center">
          <div className="layout-content-container flex flex-col w-full max-w-7xl flex-1">
            <Header />
            <main className="flex-1 pt-1 pb-5">
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {markets.map((market, index) => (
                  <MarketCard key={index} {...market} />
                ))}
              </div>
            </main>
            <Footer />
          </div>
        </div>
      </div>
    </div>
  )
}

